services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    environment:
      - ODOO_URL=https://gader-odoo-web.trzy2m.easypanel.host
    networks:
      - podcast-network

networks:
  podcast-network:
    driver: bridge
